2018-12-16 19:13:11,814 ERROR: Exception on /ntm [GET] [in c:\python\tm_final-master\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\python\TM_final-master\app\main\routes.py", line 784, in ntm
    return render_template('ntm.html',  title='NTM', form=form)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\python\TM_final-master\app\templates\ntm.html", line 47, in template
    'q0':{
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 620, in parse_tuple
    args.append(parse())
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 547, in parse_unary
    node = self.parse_postfix(node)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 676, in parse_postfix
    node = self.parse_call(node)
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\parser.py", line 767, in parse_call
    self.stream.expect('comma')
  File "c:\python\tm_final-master\venv\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'q0'
2018-12-16 19:13:35,104 INFO: Microtm startup [in C:\python\TM_final-master\app\__init__.py:46]
2018-12-16 19:25:54,527 INFO: Microtm startup [in C:\python\TM_final-master\app\__init__.py:46]
2018-12-16 19:26:54,254 INFO: Microtm startup [in C:\python\TM_final-master\app\__init__.py:46]
2018-12-16 20:00:46,275 INFO: Microtm startup [in C:\python\TM_final-master\app\__init__.py:46]
2018-12-16 20:00:53,154 ERROR: Exception on /vstup/2/dtm [GET] [in c:\python\tm_final-master\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\python\TM_final-master\app\main\routes.py", line 83, in vstup
    df, input_symbols , input_symbols_dict = table_df.table(name,druh)
  File "C:\python\TM_final-master\table\table_df.py", line 13, in table
    df, input_symbols = dtm_table(name)
  File "C:\python\TM_final-master\table\table_df.py", line 50, in dtm_table
    final_states= final_states_d
  File "C:\python\TM_final-master\turing_machine\dtm.py", line 19, in __init__
    self._init_from_formal_params(**kwargs)
  File "C:\python\TM_final-master\turing_machine\dtm.py", line 34, in _init_from_formal_params
    self.validate_self()
  File "C:\python\TM_final-master\turing_machine\dtm.py", line 125, in validate_self
    self._validate_nonfinal_initial_state()
AttributeError: 'DTM' object has no attribute '_validate_nonfinal_initial_state'
2018-12-16 20:02:12,127 INFO: Microtm startup [in C:\python\TM_final-master\app\__init__.py:46]
2018-12-16 20:06:04,984 ERROR: Exception on /vstup/43/dtm [GET] [in c:\python\tm_final-master\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\python\TM_final-master\app\main\routes.py", line 83, in vstup
    df, input_symbols , input_symbols_dict = table_df.table(name,druh)
  File "C:\python\TM_final-master\table\table_df.py", line 13, in table
    df, input_symbols = dtm_table(name)
  File "C:\python\TM_final-master\table\table_df.py", line 63, in dtm_table
    df1 = pd.DataFrame([z1], index = [dtm.final_states], columns=list(df.columns.values))
  File "c:\python\tm_final-master\venv\lib\site-packages\pandas\core\frame.py", line 369, in __init__
    arrays, columns = _to_arrays(data, columns, dtype=dtype)
  File "c:\python\tm_final-master\venv\lib\site-packages\pandas\core\frame.py", line 6284, in _to_arrays
    dtype=dtype)
  File "c:\python\tm_final-master\venv\lib\site-packages\pandas\core\frame.py", line 6363, in _list_to_arrays
    coerce_float=coerce_float)
  File "c:\python\tm_final-master\venv\lib\site-packages\pandas\core\frame.py", line 6420, in _convert_object_array
    'columns' % (len(columns), len(content)))
AssertionError: 2 columns passed, passed data had 3 columns
